<?php /** @noinspection ALL */

namespace Ydistri\Settings;

class RegionSettings {

    const REGION_LIST = [
        'Vustrya (North)' => 39,
        'Vustrya (East)' => 23,
        'Vustrya (South)' => 32,
        'Vustrya (West)' => 34,
        'Vustrya (Northwest)' => 45,
        'Vustrya (Northeast)' => 32,
        'Vustrya (Southwest)' => 27,
        'Vustrya (Southeast)' => 23,
        'Scoisau (North)' => 35,
        'Scoisau (East)' => 10,
        'Scoisau (South)' => 15,
        'Scoisau (West)' => 31,
        'Scoisau (Northwest)' => 32,
        'Scoisau (Northeast)' => 36,
        'Scoisau (Southwest)' => 46,
        'Scoisau (Southeast)' => 11,
        'Espeau (North)' => 25,
        'Espeau (East)' => 42,
        'Espeau (South)' => 48,
        'Espeau (West)' => 46,
        'Espeau (Northwest)' => 38,
        'Espeau (Northeast)' => 11,
        'Espeau (Southwest)' => 18,
        'Espeau (Southeast)' => 27,
        'Teswora (North)' => 31,
        'Teswora (East)' => 27,
        'Teswora (South)' => 38,
        'Teswora (West)' => 35,
        'Teswora (Northwest)' => 17,
        'Teswora (Northeast)' => 48,
        'Teswora (Southwest)' => 18,
        'Teswora (Southeast)' => 31,
        'Swey Whos (North)' => 17,
        'Swey Whos (East)' => 31,
        'Swey Whos (South)' => 48,
        'Swey Whos (West)' => 22,
        'Swey Whos (Northwest)' => 15,
        'Swey Whos (Northeast)' => 48,
        'Swey Whos (Southwest)' => 42,
        'Swey Whos (Southeast)' => 19,
        'Efren (North)' => 18,
        'Efren (East)' => 12,
        'Efren (South)' => 47,
        'Efren (West)' => 15,
        'Efren (Northwest)' => 25,
        'Efren (Northeast)' => 18,
        'Efren (Southwest)' => 19,
        'Efren (Southeast)' => 31,
        'Oshos (North)' => 17,
        'Oshos (East)' => 17,
        'Oshos (South)' => 43,
        'Oshos (West)' => 28,
        'Oshos (Northwest)' => 29,
        'Oshos (Northeast)' => 40,
        'Oshos (Southwest)' => 50,
        'Oshos (Southeast)' => 13,
    ];
}