<?php /** @noinspection ALL */

namespace Ydistri\Settings;

class RegionSettings {

    const REGION_LIST = [
        'Vustrya (North)' => 527,
        'Vustrya (East)' => 477,
        'Vustrya (South)' => 154,
        'Vustrya (West)' => 91,
        'Vustrya (Northwest)' => 533,
        'Vustrya (Northeast)' => 487,
        'Vustrya (Southwest)' => 405,
        'Vustrya (Southeast)' => 165,
        'Scoisau (North)' => 407,
        'Scoisau (East)' => 110,
        'Scoisau (South)' => 427,
        'Scoisau (West)' => 720,
        'Scoisau (Northwest)' => 666,
        'Scoisau (Northeast)' => 878,
        'Scoisau (Southwest)' => 118,
        'Scoisau (Southeast)' => 256,
        'Espeau (North)' => 199,
        'Espeau (East)' => 573,
        'Espeau (South)' => 815,
        'Espeau (West)' => 351,
        'Espeau (Northwest)' => 101,
        'Espeau (Northeast)' => 163,
        'Espeau (Southwest)' => 894,
        'Espeau (Southeast)' => 807,
        'Teswora (North)' => 490,
        'Teswora (East)' => 179,
        'Teswora (South)' => 54,
        'Teswora (West)' => 787,
        'Teswora (Northwest)' => 163,
        'Teswora (Northeast)' => 787,
        'Teswora (Southwest)' => 672,
        'Teswora (Southeast)' => 173,
        'Swey Whos (North)' => 404,
        'Swey Whos (East)' => 630,
        'Swey Whos (South)' => 416,
        'Swey Whos (West)' => 503,
        'Swey Whos (Northwest)' => 711,
        'Swey Whos (Northeast)' => 286,
        'Swey Whos (Southwest)' => 811,
        'Swey Whos (Southeast)' => 222,
        'Efren (North)' => 910,
        'Efren (East)' => 73,
        'Efren (South)' => 533,
        'Efren (West)' => 855,
        'Efren (Northwest)' => 612,
        'Efren (Northeast)' => 769,
        'Efren (Southwest)' => 914,
        'Efren (Southeast)' => 805,
        'Oshos (North)' => 555,
        'Oshos (East)' => 835,
        'Oshos (South)' => 89,
        'Oshos (West)' => 214,
        'Oshos (Northwest)' => 926,
        'Oshos (Northeast)' => 127,
        'Oshos (Southwest)' => 757,
        'Oshos (Southeast)' => 245,
    ];
}